baseURL = "https://www.example.org/"
theme = "bootstrap"
defaultContentLanguage = "en"

[params]
cdn = "/3rd"
timestamp = "Monday, 2 January 2006 15:04:05 MST"

[languages]
[languages.en]
languageName = "English"
title = "Title"
copyright = "2020"
weight = 1
[[languages.en.menu.header]]
identifier = "1"
title = "1"
weight = 1
[[languages.en.menu.header]]
identifier = "1-1"
title = "1-1"
url = "/1-1"
weight = 11
parent = "1"
[[languages.en.menu.header]]
identifier = "1-2"
title = "1-2"
url = "/1-2"
weight = 12
parent = "1"
[[languages.en.menu.header]]
identifier = "1-3"
title = "1-3"
url = "/1-3"
weight = 13
parent = "1"
[[languages.en.menu.header]]
identifier = "2"
title = "2"
weight = 2
[[languages.en.menu.header]]
identifier = "2-1"
title = "2-1"
url = "/2-1"
weight = 21
parent = "2"
[[languages.en.menu.header]]
identifier = "2-2"
title = "2-2"
url = "/2-2"
weight = 22
parent = "2"
[[languages.en.menu.header]]
identifier = "2-3"
title = "2-3"
url = "/2-3"
weight = 23
parent = "2"
[[languages.en.menu.header]]
identifier = "3"
title = "3"
url = "/3"
weight = 3
[[languages.en.menu.header]]
identifier = "4"
title = "4"
url = "/4"
weight = 4
[[languages.en.menu.footer]]
identifier = "about"
title = "About"
url = "/about"
weight = 1
[[languages.en.menu.footer]]
identifier = "contact"
title = "Contact"
url = "/contact"
weight = 2
[[languages.en.menu.footer]]
identifier = "team"
title = "Team"
url = "/team"
weight = 3

[languages.zh]
languageName = "中文"
title = "标题"
copyright = "2020"
weight = 2
[[languages.zh.menu.footer]]
identifier = "about"
title = "关于"
url = "/about"
weight = 1
[[languages.zh.menu.footer]]
identifier = "contact"
title = "联系"
url = "/contact"
weight = 2
[[languages.zh.menu.footer]]
identifier = "team"
title = "团队"
url = "/team"
weight = 3

